[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.intl", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts --ignore-platform-reqs"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
